### ISSUE TITLE
prevent ban

### ISSUE THREAD

**Issue by atilamagalhaes4** [Dantes-Dungeon/safe-exit#2]
It was recently announced that using emulators in developer mode will be subject to a ban. Do you intend to add some option to clean the registry or history to prevent microsoft from knowing that it was used ??
Thank you for the response time and congratulations on the project, simply amazing !!!

**Comment by tunip3** [comment]
> It was recently announced that using emulators in developer mode will be subject to a ban. Do you intend to add some option to clean the registry or history to prevent microsoft from knowing that it was used ?? Thank you for the response time and congratulations on the project, simply amazing !!!

using emulators on dev mode does not result in a ban, only on retail at this time to the best of my knowledge
